# Generated by Django 3.2.10 on 2023-12-15 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', "Ім'я не може містити цифри.")])),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('passport_data', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('married', 'Одружений/заміжня'), ('single', 'Не одружений/не заміжня')], max_length=10, null=True)),
                ('working_hours_per_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
